import {
    MenuUnfoldOutlined,
    MenuFoldOutlined,
    EyeOutlined,
    CarOutlined,
    CustomerServiceOutlined,
    YuqueOutlined,
    RiseOutlined,
    CloseOutlined,
    CheckOutlined,
    ExperimentOutlined,
    LikeOutlined,
    UnorderedListOutlined,
    PieChartOutlined,
    CaretUpOutlined,
    CaretDownOutlined,
    MailOutlined,
    DeleteOutlined,
    SettingOutlined
} from "@ant-design/icons";

export default {
    MenuUnfoldOutlined,
    MenuFoldOutlined,
    EyeOutlined,
    CarOutlined,
    CustomerServiceOutlined,
    YuqueOutlined,
    RiseOutlined,
    CloseOutlined,
    CheckOutlined,
    ExperimentOutlined,
    LikeOutlined,
    UnorderedListOutlined,
    PieChartOutlined,
    CaretUpOutlined,
    CaretDownOutlined,
    MailOutlined,
    DeleteOutlined,
    SettingOutlined
};