export const CLEAR_VIDEOS = "video.reducer/CLEAR_VIDEOS";
export const GET_VIDEOS = "video.reducer/GET_VIDEOS";
export const GET_VIDEO_DETAIL = "video.reducer/GET_VIDEO_DETAIL";
export const GET_SUBSCRIPTION_VIDEOS = "video.reducer/GET_SUBSCRIPTION_VIDEOS";
export const SEARCH_VIDEO = "video.reducer/SEARCH_VIDEO";
export const SET_VIEW_VIDEO = "video.reducer/SET_VIEW_VIDEO";
export const GET_VIDEOS_BY_CATEGORY = "video.reducer/GET_VIDEOS_BY_CATEGORY";
export const IS_SEARCHING = "video.reducer/IS_SEARCHING";
export const SET_CATEGORY_TYPE ="video.reducer/SET_CATEGORY_TYPE";